spatie/ssl-certificate

- README.md
Looks like the example code at the top of the readme refers to an older version?
> Updated a possible typo in Readme

- README.md
- src/Downloader.php
- src/SslCertificate.php
- tests/SslCertificateTest.php
Added method and tests for getting an SSL's signing alogorithm
Update readme as well
And ensure I'm doing PSR2 right
> Add method to get signing Algorithm

- src/SslCertificate.php
- tests/SslCertificateTest.php
The wildcard matching is currently too simple and incorrect. 
It's explained the simplest on Wikipedia: https://en.wikipedia.org/wiki/Wildcard_certificate#Example
With thanks to @JorisvanW for simplifying the implementation.
> Fix wildcard matching

- CHANGELOG.md
- src/Downloader.php
- src/SslCertificate.php
This PR fixes 2 things;
1) It adds `__toString()` on the `SslCertificate` to allow objects to be used in array filters like `array_unique()`
2) It bugfixes a problem where wildcard certificates get reported in both the `peer_certificate` as well as `peer_certificate_chain`, giving the impression that a certificate exists twice (which it doesn't). In that case, duplicate certificates get removed and only its unique values remain.
> Add Object-to-String casting and wildcard chain bugfix

- composer.json
I believe there should be no reason why this cool library should install phpunit when `--no-dev` is specified.
> Move "phpunit-snapshot-assertions" to dev dependencies

- src/SslCertificate.php
Often times, the main domain is repeated in the SAN again, causing it to appear twice in the getDomains() list. Filter only the unique values, there's no point in reporting domains twice or more.
> Only return unique domain names

- src/SslCertificate.php
In some rare cases, a Common Name consists of multiple domains, instead of a single one. This covers that edge case and returns the first element if it's an array.
> getDomain(): if the subject consists of more than 1 domain, pick the first

- src/SslCertificate.php
ref: https://www.thesslstore.com/blog/security-changes-in-chrome-58/
```
Many people don’t know that the “Common Name” field of an SSL certificate, which contains the domain name the certificate is valid for, was actually phased-out via RFC nearly two decades ago. Instead, the SAN (Subject Alternative Name) field is the proper place to list the domain(s).
However, this has been ignored and for many years the Common Name field was exclusively used. Chrome is finally fed up with the field that refuses to die. In Chrome 58, the Common Name field is now ignored entirely.
```
> getDomains(): do not use the Common Name, obsoleted

- src/Url.php
This is a workaround for failed IDN validations. This appears to be a known, yet unfixed, problem in PHP:
- https://bugs.php.net/bug.php?id=53474
- https://bugs.php.net/bug.php?id=73176
`idn_to_ascii()` is used to convert the IDN to an ASCII representation for the validation, afterwards that ASCII form is used to make the actual calls to the URL. Libcurl handles the rest.
> Convert IDN to ASCII before attempting to validate

- src/SslCertificate.php
1.1.1.1 is CloudFlare's DNS IP address that has a valid SSL certificate. But this package doesn't validate that IP address' SSL certificate. My PR fixes that issue.
> Fix SSL check for IP addresses that serve a valid SSL, i.e. 1.1.1.1

- src/Url.php
Environments running PHP7.1 with an ICU version < 4.6 will not have the 'INTL_IDNA_VARIANT_UTS46' defined. Even though the `idn_to_ascii()` function exists.
This will check for the constant, and fall back to using the `idn_to_ascii()` defaults if it does not exist.
> Check for missing 'INTL_IDNA_VARIANT_UTS46' to constant

- README.md
- src/Downloader.php
- src/SslCertificate.php
- tests/DownloaderTest.php
This can be used to check whether a particular IP address has a certificate matching the provided host name. One of the use cases would be ensuring backend compliance - this would allow you to check the certificate's expiry date and validity on the origin servers as well, e.g. if they are behind a load balancer or the traffic is proxied through Cloudflare.
> Add function to get certificate for hostname from IP address

- src/Downloader.php
If the `Downloader` is asked to fetch a certificate from an unresolvable / un-connectable URL then `stream_socket_client()` will generate PHP warnings. 
Test code:
```php
<?php
use Spatie\SslCertificate\SslCertificate;
require 'vendor/autoload.php';
try {
$certificate = SslCertificate::createForHostName('www.non-existent-domain-name-here.com');
echo "Succeeded";
} catch (\Exception $e) {
echo "Failed";
}
```
Expected output:
```$ php test.php
Failed
```
Actual output:
```$ php test.php
PHP Warning:  stream_socket_client(): php_network_getaddresses: getaddrinfo failed: nodename nor servname provided, or not known in /ssl-certificate/src/Downloader.php on line 138
Warning: stream_socket_client(): php_network_getaddresses: getaddrinfo failed: nodename nor servname provided, or not known in …
```
> Silence warnings from stream_socket_client() in Spatie\SslCertificate\Downloader()

- README.md
- src/Downloader.php
- src/SslCertificate.php
I believe downloading invalid certificates is a pretty common use case (see: #69 #124 #82 ) so this PR adds an argument to `createForHostname` to make it easy to enable downloading of invalid certificates. Also documents this option.
> Add option to disable certificate validation in createForHostName

- phpunit.xml.dist
- tests/SslCertificateFromStringTest.php
- tests/SslCertificateTest.php
- Improve PHPUnit fixtures.
- Using the `vendor/bin/phpunit --migrate-configuration` command to fix following PHPunit warning when running the `vendor/bin/phpunit` command:
```
Warning:       Your XML configuration validates against a deprecated schema.
Suggestion:    Migrate your XML configuration using "--migrate-configuration"!
```
> Improve PHPUnit fixtures and configuration

- src/SslCertificate.php
- tests/SslCertificateFromStringTest.php
Information about the organization is in `['issuer']['O']` and not in `['subject']['O']`
> Fix getOrganization method which always returned an empty result

- src/Exceptions/CouldNotDownloadCertificate/UnknownError.php
I need the original, technical message, not the full human readable exception message. With this change, that error message is retrievable.
----
Instead of
> Could not download certificate for host `example.com` because Could not connect to `example.com`.
I only want
> Could not connect to `example.com`.
> Keep original unknown error message

- src/Downloader.php
Hi,
This is great library, but I have 1 issue : 
- The error message does not show connected TCP port number. ( This pull request may resolve this issue )
Thanks for your contributions.
> Display connecting port in error message

- src/Downloader.php
`stream_socket_client()`'s `$errorDescription` misses a lot of error message. Most of the time (in my cases) it's just an empty string after a connection failure. But the exception is always a useful pretty error message. `hostDoesNotExist`, `noCertificateInstalled` and `unknownError` after that still work the same.
> Use stream_socket_client() exception for better message

- src/Downloader.php
Without this change, PHP warnings may pop-up:
```
PHP Warning:  stream_socket_client(): php_network_getaddresses: getaddrinfo for xxxx.xx failed: Name or service not known in vendor/spatie/ssl-certificate/src/Downloader.php on line 185
```
Seems to have been changed with https://github.com/spatie/ssl-certificate/pull/183. From what I can see, even when suppressing, error handling still happens.
> Suppress `stream_socket_client` warnings

- src/SslCertificate.php
- tests/SslCertificateSerializationTest.php
I'm running into issues where the `SslCertificate` instance can't be serialized for a queue job, due to binary "malformed UTF-8" characters is some of the `publicKeyDetail`.
I'm specifically running into this in the `laravel-uptime-monitor` package, when a certificate is included in a queued `CertificateCheckSucceeded` event. See here:
https://github.com/spatie/laravel-uptime-monitor/discussions/359
This PR base64 encodes the `publicKeyDetail` part of the certificate when serializing, and handles decoding on unserialize.
I have this fork installed in my own app, and have verified it resolves the issue.
Test case added to verify serialize/unserialize works properly, and that we can `json_encode` a serialized certificate.
> Base64 encode serialized publicKeyDetail

- src/SslCertificate.php
Fixes WARNING - Implicit conversion from float 89.99998842592592 to int loses precision in (...)/spatie/ssl-certificate/src/SslCertificate.php on line 165
Reason:
diffInDays: float
> Implicit conversion from float to int Warning

- src/SslCertificate.php
This MR fix those deprecation warning appeared in PHP 8.4:
```
PHP Deprecated:  Spatie\SslCertificate\SslCertificate::isValid(): Implicitly marking parameter $url as nullable is deprecated, the explicit nullable type must be used instead
PHP Deprecated:  Spatie\SslCertificate\SslCertificate::isValidUntil(): Implicitly marking parameter $url as nullable is deprecated, the explicit nullable type must be used instead
```
> Fix PHP 8.4 implicitly marking parameter deprecation
